### PR TITLE
Language, structure, and process updates

### PR DESCRIPTION
**Pull request by bglendenning**
* update README to be more thorough with greater clarity
* update tutorial structures for consistency
* reduce complexity of plume and scene tutorials for greater focus
* remove reliance on virtualenv by using IPython pip magic command
* rename tutorial files for consistency & navigational clarity
* add clarity to STAC token usage script in STAC CMF tutorial

Rendered files in this branch:
* [README](https://github.com/carbon-mapper/platform-public/blob/e8ae7172a9c5cb118af60e5f51b6b55ff1e94f05/tutorials/README.md)
* [plumes](https://github.com/carbon-mapper/platform-public/blob/e8ae7172a9c5cb118af60e5f51b6b55ff1e94f05/tutorials/download_plumes_csv.ipynb)
* [scenes](https://github.com/carbon-mapper/platform-public/blob/e8ae7172a9c5cb118af60e5f51b6b55ff1e94f05/tutorials/download_scenes_geopkackage.ipynb)
* [STAC token](https://github.com/carbon-mapper/platform-public/blob/e8ae7172a9c5cb118af60e5f51b6b55ff1e94f05/tutorials/scoped_token.ipynb)
* [L2B CMF asset](https://github.com/carbon-mapper/platform-public/blob/e8ae7172a9c5cb118af60e5f51b6b55ff1e94f05/tutorials/stac/download_l2b_cmf_asset.ipynb)

### CODE REVIEW

**Comment by alexdiamondbv** [comment]
Small typo here "geopkackage"

Screenshot 2024-08-19 at 8 15 51 AM

**Comment by bglendenning** [comment]
@alexdiamondbv fixed that typo a couple days ago btw.

**Review by alexdiamondbv — APPROVED** [review]
In the README:

https://api.platform.carbonmapper.org/api/v1/docs

Should be:

https://api.carbonmapper.org/api/v1/docs

**Comment by bglendenning** [comment]
Oh man, it's always the little things that hit the hardest.

**Review by demiurg — APPROVED** [review]
This looks good!

**Pull request merged**
